### PR TITLE
Use the url where the schema is mounted in emails links

### LINKED ISSUE #105: Separate endpoint url for mailers even if mounting the gem in your own schema
### Describe the bug
Mailers include a link to be clicked and the base url for these is always fixed to the gem's graphql controller. This won't work when you mount the auth schema in your very own GQL schema.

We need to find a way to capture the currentUrl on the signUp, sendPasswordReset and resendConfirmation mutations.

If anyone is facing an issue with this, until fixed I would recommend also mounting this gem in your routes file. This way the path will be available when you click on the links. You can pass the only option as you only need the query operations available.

```ruby
mount_graphql_devise_for('User', only: [: check_password_token, : send_password_reset])
```
The route will be mounted at `/graphql_auth` but the mailer will pick this up and generate the right url.

### PR DESCRIPTION
**Pull request by 00dav00**
Fix #105 

- [x] Update the reset password email
- [x] Update the confirm account email

### CODE REVIEW

File: lib/graphql_devise/mutations/send_password_reset.rb [hunk 1]
```diff
@@ -16,7 +16,8 @@ def resolve(email:, redirect_url:)
             email:         email,
             provider:      'email',
             redirect_url:  redirect_url,
-            template_path: ['graphql_devise/mailer']
+            template_path: ['graphql_devise/mailer'],
+            **controller.params.permit('controller', 'action').to_h.symbolize_keys
```
Comment (mcelicalderon) [inline lib/graphql_devise/mutations/send_password_reset.rb:20]: 👌

File: spec/dummy/app/graphql/dummy_schema.rb [hunk 2]
```diff
@@ -3,7 +3,10 @@ class DummySchema < GraphQL::Schema
     query:            Types::QueryType,
     mutation:         Types::MutationType,
     resource_loaders: [
-      GraphqlDevise::ResourceLoader.new('User', only: [:login, :confirm_account]),
+      GraphqlDevise::ResourceLoader.new(
+        'User',
```
Comment (mcelicalderon) [inline spec/dummy/app/graphql/dummy_schema.rb:7]: Might be better to test with a model that didn't also mount the queries on a separate schema. So it fails without your change
